### PR TITLE
locust: fix compatibility with locust v1

### PR DESCRIPTION
**Pull request by jrcastro2**
* Fixes locustfile.py for locust v1

* Updates package name

### CODE REVIEW

**Review by ppanero — COMMENTED** [review]
Just a compatibility question. Since now it is `locust` and not `locustio` I guess there is no issues with imports (i.e. the change from `HttpLocust` to `HttpUser`).

However, just for clarification, would it be worth to add the locust version? or is it an overkill?

Nice job! 🚀

**Comment by jrcastro2** [comment]
@ppanero you are right, with locustio there are no import problems, but it is necessary to pin the version now, just updating the README with `pipenv run pip install locustio==0.14.6` should do it, otherwise it will fail.

Thanks!

**Comment by ppanero** [comment]
Hi @jrcastro2! Sorry, I think i expressed myself wrong. I was not against updating, using newer versions is always better. Even more if now is a 1.x version rather than dev 0.x.

I think the previous changes you implemented were better 😅 I was just trying to understand the compatibility :)

Sorry for the mess

**Review by ppanero — APPROVED** [review]

**Comment by ntarocco** [comment]
LGTM! 🚀 thanks @jrcastro2 for fixing this! :)

**Pull request merged**
